title: Anjali Bhosale # your name (or website title) here
logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Frontend Developer
  <br><br>
  <a href="mailto:bhosaleanjali575@gmail.com">bhosaleanjali575@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/anjali-bhosale-18826518b/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/anjalibhosale96/">Gihub</a> 
theme: jekyll-theme-minimal
